sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
  - '7'
  - '6'
script:
  - yarn build
after_success:
  - make docker-all
branches:
  only:
    - master
    - /^greenkeeper/.*$/
