sudo: false
language: node
cache:
  directories:
    - node_modules
notifications:
  email: false
before_script:
  - npm install -g yarn
script:
  - make docker-all
node_js:
  - node
branches:
  only:
    - master
