sudo: false
language: node
node_js:
  - 8
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
before_script:
  - npm install -g yarn
script:
  - make docker-all
branches:
  only:
    - master
