sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
script:
  - make docker-all
branches:
  only:
    - master
    - /^greenkeeper/.*$/
