sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_install:
 - echo $TEST_KEY > ~/.ssh/id_rsa.pub
script:
  - make docker-all
branches:
  only:
    - master
    - /^greenkeeper/.*$/
