export const ON_COUNTY_CLICK = "ON_COUNTY_CLICK";
export const ON_ZOOM_CHANGE = "ON_ZOOM_CHANGE";
export const FETCH_COUNTIES_AND_DROP_MARKERS =
  "FETCH_COUNTIES_AND_DROP_MARKERS";
export const VALIDATE_ZIP_CODE = "VALIDATE_ZIP_CODE";
export const SEARCH_ZIP_CODE = "SEARCH_ZIP_CODE";
