export const ON_COUNTY_CLICK = "ON_COUNTY_CLICK";
export const ON_ZOOM_CHANGE = "ON_ZOOM_CHANGE";
export const ON_MOVE = "ON_MOVE";
export const FETCH_COUNTIES_AND_DROP_MARKERS =
  "FETCH_COUNTIES_AND_DROP_MARKERS";
export const VALIDATE_ZIP_CODE = "VALIDATE_ZIP_CODE";
export const SEARCH_ZIP_CODE = "SEARCH_ZIP_CODE";
export const POPULATE_ZIP_CODE_MAP = "POPULATE_ZIP_CODE_MAP";
export const SET_INPUT_VALUE = "SET_INPUT_VALUE";
